#pragma once
// AUTO-GENERATED (tools/fonts/gen.py): JetBrains Mono epdiy fonts.
// Naming: JB_<weight><px> — R=Regular M=Medium B=Bold X=ExtraBold.
#include "JB_R14.h"
#include "JB_R15.h"
#include "JB_R16.h"
#include "JB_R17.h"
#include "JB_R19.h"
#include "JB_M17.h"
#include "JB_M19.h"
#include "JB_M20.h"
#include "JB_M22.h"
#include "JB_B14.h"
#include "JB_B15.h"
#include "JB_B16.h"
#include "JB_B17.h"
#include "JB_B19.h"
#include "JB_B20.h"
#include "JB_B22.h"
#include "JB_B24.h"
#include "JB_X24.h"
#include "JB_X34.h"
#include "JB_X36.h"
#include "JB_X42.h"
#include "JB_X44.h"
#include "JB_X52.h"
