#!/usr/bin/env python3
"""Generate (once) the Ed25519 signing keypair for VulnCast firmware auto-updates.

The device verifies every update manifest against a PUBLIC key baked into the firmware
(include/update_pubkey.h — safe to commit). The matching PRIVATE key signs releases and
must NEVER be committed or uploaded: it is written OUTSIDE the repo working tree.

  private key : $VULNCAST_UPDATE_KEY  (default: ~/.vulncast/update_ed25519.key), chmod 600
  public key  : include/update_pubkey.h  (C array, committed)

Idempotent: if the private key already exists it is reused (never overwritten) and only the
public header is (re)generated. The private key bytes are NEVER printed. Run once:

  python3 scripts/gen_update_key.py

Sign releases later with scripts/sign_release.py (reads the same private key).
"""
import os
import sys

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = os.path.join(REPO, "include", "update_pubkey.h")
KEY_PATH = os.environ.get("VULNCAST_UPDATE_KEY", os.path.expanduser("~/.vulncast/update_ed25519.key"))


def load_or_create_private():
    """Return the 32-byte Ed25519 private seed, creating + persisting it once if absent."""
    if os.path.exists(KEY_PATH):
        with open(KEY_PATH) as f:
            seed = bytes.fromhex(f.read().split("#", 1)[0].strip())
        if len(seed) != 32:
            sys.exit(f"error: {KEY_PATH} does not contain a 32-byte hex seed")
        return Ed25519PrivateKey.from_private_bytes(seed), False
    # Create a new key OUTSIDE the repo, locked down (0700 dir, 0600 file).
    priv = Ed25519PrivateKey.generate()
    seed = priv.private_bytes(serialization.Encoding.Raw, serialization.PrivateFormat.Raw,
                              serialization.NoEncryption())
    d = os.path.dirname(KEY_PATH)
    if d and not os.path.isdir(d):
        os.makedirs(d, mode=0o700, exist_ok=True)
    # Write with restrictive perms from the start (open with 0600 before writing bytes).
    fd = os.open(KEY_PATH, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "w") as f:
        f.write(seed.hex() + "  # VulnCast Ed25519 update-signing PRIVATE key — never commit/upload\n")
    os.chmod(KEY_PATH, 0o600)
    return priv, True


def write_header(pub_raw: bytes):
    rows = []
    for i in range(0, len(pub_raw), 12):
        rows.append("    " + ", ".join(f"0x{b:02X}" for b in pub_raw[i:i + 12]) + ",")
    body = "\n".join(rows).rstrip(",")
    os.makedirs(os.path.dirname(HEADER), exist_ok=True)
    with open(HEADER, "w") as f:
        f.write(
            "// Auto-generated by scripts/gen_update_key.py — DO NOT EDIT BY HAND.\n"
            "//\n"
            "// Ed25519 PUBLIC key used to verify signed firmware update manifests (update.json).\n"
            "// A public key is NOT a secret — safe to commit. The matching PRIVATE key signs\n"
            "// releases and lives OUTSIDE this repo (see scripts/gen_update_key.py); it is never\n"
            "// committed or uploaded.\n"
            "#pragma once\n"
            "#include <stdint.h>\n\n"
            "static const uint8_t UPDATE_PUBKEY[32] = {\n"
            f"{body}\n"
            "};\n")


def main():
    priv, created = load_or_create_private()
    pub_raw = priv.public_key().public_bytes(serialization.Encoding.Raw,
                                             serialization.PublicFormat.Raw)
    write_header(pub_raw)
    # Only ever print the PUBLIC key + paths — never the private key.
    print(f"private key : {KEY_PATH}  ({'created' if created else 'reused, unchanged'})")
    print(f"public key  : {HEADER}")
    print(f"pubkey (hex): {pub_raw.hex()}")
    if created:
        print("\nBack this private key up offline. Losing it means no future signed updates.")
        print("It is git-ignored and outside the repo; keep it that way.")


if __name__ == "__main__":
    main()
