#!/usr/bin/env python3
"""Sign a VulnCast firmware update manifest (update.json) with the Ed25519 release key.

The device verifies the signature over the exact canonical message:

    version + "\\n" + url + "\\n" + size + "\\n" + sha256hex

against the PUBLIC key baked into the firmware (include/update_pubkey.h). Every field the device
trusts is covered. Signing this (not the 1.7 MB image) keeps ed25519's internal SHA-512 tiny; the
image is bound because its sha256 must match at install time.

The PRIVATE key is read from $VULNCAST_UPDATE_KEY (default ~/.vulncast/update_ed25519.key) and is NEVER
printed. Generate it once with scripts/gen_update_key.py.

Usage:
  # from a built app image (computes size + sha256), writing the published manifest:
  python3 scripts/sign_manifest.py --version 1.0.4 \\
      --url https://github.com/vulnersCom/VulnCast/releases/download/v1.0.4/vulncast-1.0.4-app.bin \\
      --bin .pio/build/vulncast/firmware.bin --out flasher/update.json

  # regenerate the on-device crypto self-test vector header (include/update_selftest.h):
  python3 scripts/sign_manifest.py --emit-selftest
"""
import argparse
import base64
import hashlib
import json
import os
import sys

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KEY_PATH = os.environ.get("VULNCAST_UPDATE_KEY", os.path.expanduser("~/.vulncast/update_ed25519.key"))
SELFTEST_HEADER = os.path.join(REPO, "include", "update_selftest.h")


def load_private():
    if not os.path.exists(KEY_PATH):
        sys.exit(f"error: private key not found at {KEY_PATH} — run scripts/gen_update_key.py first")
    with open(KEY_PATH) as f:
        seed = bytes.fromhex(f.read().split("#", 1)[0].strip())
    return Ed25519PrivateKey.from_private_bytes(seed)


def signed_message(version: str, url: str, size: int, sha256hex: str) -> bytes:
    # MUST byte-match Updater::verifyManifest (updater.cpp).
    return f"{version}\n{url}\n{size}\n{sha256hex}".encode()


def _c_bytes(name, data, as_macro=False):
    elems = [f"0x{b:02X}" for b in data]
    rows = [", ".join(elems[i:i + 12]) for i in range(0, len(elems), 12)]
    if as_macro:
        joined = ", \\\n    ".join(rows)
        return f"#define {name} {{ \\\n    {joined} }}\n"
    body = ",\n".join("    " + r for r in rows)
    return f"static const uint8_t {name}[{len(data)}] = {{\n{body}\n}};"


def emit_selftest(priv):
    """Write include/update_selftest.h — a fixed signed vector for the device's Ed25519 self-test."""
    version, url, size = "1.0.4-selftest", "https://example.invalid/fw.bin", 1763120
    sha256hex = hashlib.sha256(b"vulncast-selftest").hexdigest()
    msg = signed_message(version, url, size, sha256hex)
    sig = priv.sign(msg)
    with open(SELFTEST_HEADER, "w") as f:
        f.write("// Auto-generated by scripts/sign_manifest.py --emit-selftest — DO NOT EDIT.\n"
                "// A fixed manifest signature (over the canonical message) used by Updater::selfTest()\n"
                "// to prove the on-device Ed25519 verifier matches the host signer + the baked pubkey.\n"
                "// Public data — safe to commit.\n#pragma once\n\n")
        f.write(f"#define SELFTEST_MSG_LEN {len(msg)}\n")
        f.write(_c_bytes("SELFTEST_MSG", msg, as_macro=True))
        f.write(_c_bytes("SELFTEST_SIG", sig, as_macro=True))
    print(f"wrote {SELFTEST_HEADER} (msg {len(msg)}B)")


def main():
    ap = argparse.ArgumentParser(description="Sign a VulnCast update manifest")
    ap.add_argument("--version")
    ap.add_argument("--url", default="")
    ap.add_argument("--bin", help="app image to hash (computes sha256 + size)")
    ap.add_argument("--sha256", help="explicit image SHA-256 (64 hex) if --bin is not given")
    ap.add_argument("--size", type=int, default=0)
    ap.add_argument("--out", help="write update.json here")
    ap.add_argument("--emit-selftest", action="store_true", help="(re)generate include/update_selftest.h")
    args = ap.parse_args()

    priv = load_private()

    if args.emit_selftest:
        emit_selftest(priv)
        return

    if not args.version:
        sys.exit("error: --version is required")
    if args.bin:
        data = open(args.bin, "rb").read()
        sha_hex, size = hashlib.sha256(data).hexdigest(), len(data)
    elif args.sha256:
        sha_hex, size = args.sha256.lower(), args.size
        if len(sha_hex) != 64:
            sys.exit("error: --sha256 must be 64 hex chars")
    else:
        sys.exit("error: provide --bin or --sha256")

    sig = priv.sign(signed_message(args.version, args.url, size, sha_hex))
    manifest = {
        "version": args.version,
        "url": args.url,
        "size": size,
        "sha256": sha_hex,
        "sig": base64.b64encode(sig).decode(),
    }
    out = json.dumps(manifest, indent=2)
    if args.out:
        with open(args.out, "w") as f:
            f.write(out + "\n")
        print(f"wrote {args.out}")
    print(out)


if __name__ == "__main__":
    main()
